name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
env:
  GOOGLE_REGION: europe-north1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{env.GOOGLE_REGION}}-docker.pkg.dev --quiet
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/bake-action@v1
        with:
          files: go-services/docker-bake.hcl

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/terraform/10_shared
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{env.GOOGLE_REGION}}-docker.pkg.dev --quiet
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.4
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Apply
        run: terraform apply --var-file=vars/${{env.TF_WORKSPACE}}.tfvars -auto-approve
        env:
         TF_WORKSPACE: staging
