name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GOOGLE_REGION: europe-north1
  TERRAFORM_VERSION: 1.1.4
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{env.GOOGLE_REGION}}-docker.pkg.dev --quiet
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/bake-action@v1
        with:
          files: go-services/docker-bake.hcl
  deploy-staging:
    name: Deployment to staging
    runs-on: ubuntu-latest
    needs: [build]
    environment: staging
    env:
      TF_WORKSPACE: staging
      WORKING-DIRECTORY: infrastructure/terraform/10_shared
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{env.GOOGLE_REGION}}-docker.pkg.dev --quiet
      - uses: ./.github/actions/terraform
        with:
          environment: ${{ env.TF_WORKSPACE }}
          terraform-version: ${{ env.TERRAFORM_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ env.WORKING-DIRECTORY }}

  deploy-production:
    name: Deployment to production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    environment: production
    env:
      TF_WORKSPACE: production
      WORKING-DIRECTORY: infrastructure/terraform/10_shared
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker
        run: gcloud auth configure-docker ${{env.GOOGLE_REGION}}-docker.pkg.dev --quiet
      - uses: ./.github/actions/terraform
        with:
          environment: ${{ env.TF_WORKSPACE }}
          terraform-version: ${{ env.TERRAFORM_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
