name: tfsec
on:
  - pull_request
env:
  TERRAFORM_VERSION: 1.1.4
jobs:
  tfsec:
    name: Check terraform security
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    strategy:
      matrix:
        path:
          - infrastructure/terraform/00_init
          - infrastructure/terraform/10_shared
    steps:
      - uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        run: terraform init -input=false
      - name: Run tfsec on infrastructure/terraform/00_init
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: ${{ matrix.path }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
